### PR TITLE
[Draft] - Custom Ternary Operator in Swift

### PR DESCRIPTION
**Pull request by m0hitnnd**
https://github.com/DiscardableR/DiscardableR.github.io/pull/4/files#diff-b2783642c428b3b0546be0696c7aa4b08789c68b73135653bd16e22c0a1e4bfe

### CODE REVIEW

**Comment by m0hitnnd** [comment]
Screenshot 2021-03-08 at 9 25 13 PM

**Comment by shahrukhalam** [comment]
Cool 💯

**Comment by m0hitnnd** [comment]
Screenshot 2021-03-08 at 9 34 43 PM

**Comment by m0hitnnd** [comment]
Screenshot 2021-03-08 at 9 35 22 PM

**Comment by m0hitnnd** [comment]
Screenshot 2021-03-08 at 9 36 02 PM

**Comment by m0hitnnd** [comment]
Screenshot 2021-03-08 at 9 36 47 PM

**Comment by m0hitnnd** [comment]
Screenshot 2021-03-08 at 9 38 11 PM

**Comment by m0hitnnd** [comment]
Screenshot 2021-03-08 at 9 38 55 PM

**Comment by m0hitnnd** [comment]
Screenshot 2021-03-08 at 9 39 45 PM

**Comment by shahrukhalam** [comment]
W.R.T [1](https://github.com/DiscardableR/DiscardableR.github.io/pull/4#issuecomment-792850784):
- I think it starts with little context or pre-text. It's on the face. We could add an intro something like this:

> In our everyday Life, we are constantly taking decisions somewhere or the other at different cross-paths. Our mind consciously evaluates "If first path, then what? If second path, then what?" & Code is no different except we often take the right path in code.

- May be we can make the code example more relatable, something like:
```
var god: String?
let result: String
if god == .some {
    result = "I have found God"
} else {
    result = "Mercy! Please show Yourself."
}
```

- **Ternary** operator example can use `.none` or `.some`

**Comment by m0hitnnd** [comment]
> W.R.T [1](https://github.com/DiscardableR/DiscardableR.github.io/pull/4#issuecomment-792850784):
> 
> * I think it starts with little context or pre-text. It's on the face. We could add an intro something like this:
> 
> > In our everyday Life, we are constantly taking decisions somewhere or the other at different cross-paths. Our mind consciously evaluates "If first path, then what? If second path, then what?" & Code is no different except we often take the right path in code.
> 
> * May be we can make the code example more relatable, something like:
> 
> ```
> var god: String?
> let result: String
> if god == .some {
>     result = "I have found God"
> } else {
>     result = "Mercy! Please show Yourself."
> }
> ```
> 
> * **Ternary** operator example can use `.none` or `.some`

Thanks, @shahrukhalam . I will put more thought into this and update it.

**Comment by shahrukhalam** [comment]
W.R.T [2](https://github.com/DiscardableR/DiscardableR.github.io/pull/4#issuecomment-792859640)

- When I was reading it, the last paragraph & the line above that (Here $0 is unwrapped value), it felt like this way is already there in Swift. May be we can clarify the **custom** part from the start.

**Comment by shahrukhalam** [comment]
W.R.T [3](https://github.com/DiscardableR/DiscardableR.github.io/pull/4#issuecomment-792860270):

It’s awesome.

Just felt little off on the line ‘Infact, we can’t create ternary operator in Swift’ as we started out saying let’s build one. May be we can say something like ‘Surprise Surprise, we can’t build one, at least the usual way’ how we are used to.

**Comment by shahrukhalam** [comment]
W.R.T [5](https://github.com/DiscardableR/DiscardableR.github.io/pull/4#issuecomment-792861561):
- We can inform reader upfront that `!` has more/less/equal precedence than `|` if he/see doesn't chose to go through the link.
- Grammar: `operators will be grouped`
- Also we can show the meaning of _"operators will be grouped, left or right"_ for noobs

**Comment by shahrukhalam** [comment]
W.R.T [6](https://github.com/DiscardableR/DiscardableR.github.io/pull/4#issuecomment-792863559):
- We can also show `let result2` without the **Type** String just to showcase the power of Compiler & our Effort

**Comment by shahrukhalam** [comment]
W.R.T [7](https://github.com/DiscardableR/DiscardableR.github.io/pull/4#issuecomment-792863932):
- It's coming from a preference standpoint, I think we can give links which are more meaningful like
  - Apple Documentation on [Operator Declarations]()
  - Swift Documentation on [Basic Operators]()

**Comment by arjunbaru** [comment]
Great job on the Article 👏🏻🔥

3 Things i would like you to consider:

1. Statement which says: "@escaping closure is marked because it was not called in function". IMO if we are returning/storing a closure, it should be the main reason its called escaping as it is beyond local scope. 

2. @autoclosure we used. we can reason it better by saying as this statement { "blah" } is a self resulting statement and doesn't have a body. we can improve it further by marking it as @autoclosure 

3. This article should be marked as **Intermediate** as it has a lot of Jargons.

**Comment by kmuralidharan91** [comment]
1. Little intro as @shahrukhalam mentioned will make it cool
2. It's definitely an intermediate level 
3. the ! and | functions can have a little bit more clear explanation, it took me two times to read and understand (it's my personal feel)
4. associative and precedence part can be explained with some examples if possible.

👍🏼

**Comment by m0hitnnd** [comment]
@MuralidharanKathiresan @shahrukhalam @arjunbaru Have addressed all the suggestions in the latest [commit](https://github.com/DiscardableR/DiscardableR.github.io/pull/4/commits/f48c89ccd1459353e3b9160b6d4504070cd62302). Do verify once and let's merge this.

**Comment by m0hitnnd** [comment]
> Great job on the Article 👏🏻🔥
> 
> 3 Things i would like you to consider:
> 
> 1. Statement which says: "@escaping closure is marked because it was not called in function". IMO if we are returning/storing a closure, it should be the main reason its called escaping as it is beyond local scope.
> 2. @autoclosure we used. we can reason it better by saying as this statement { "blah" } is a self resulting statement and doesn't have a body. we can improve it further by marking it as @autoclosure
> 3. This article should be marked as **Intermediate** as it has a lot of Jargons.

@arjunbaru We Will have to see how we can mark an article as Intermediate or Beginner or Advanced. Maybe use Tags 🤔.  Let's see. We will find a good way and create a separate PR for it.

**Comment by m0hitnnd** [comment]
> 1. Little intro as @shahrukhalam mentioned will make it cool
> 2. It's definitely an intermediate level
> 3. the ! and | functions can have a little bit more clear explanation, it took me two times to read and understand (it's my personal feel)
> 4. associative and precedence part can be explained with some examples if possible.
> 
> 👍🏼

Yoo @MuralidharanKathiresan added what @shahrukhalam suggested regarding the intro. 
For the 3rd point, have tried to add more explanation, but I was thinking if we can add a gif or something to explain, that would be much easier to understand. Didn't find any good and easy way to do that. I Will research this more and will create a separate PR for this.

For the 4th point, I have added more explanation, do check it.

**Comment by m0hitnnd** [comment]
> W.R.T [7](https://github.com/DiscardableR/DiscardableR.github.io/pull/4#issuecomment-792863932):
> 
> * It's coming from a preference standpoint, I think we can give links which are more meaningful like
>   
>   * Apple Documentation on Operator Declarations
>   * Swift Documentation on Basic Operators

Done ✅  Thanks for the suggestion :)

**Comment by m0hitnnd** [comment]
> W.R.T [6](https://github.com/DiscardableR/DiscardableR.github.io/pull/4#issuecomment-792863559):
> 
> * We can also show `let result2` without the **Type** String just to showcase the power of Compiler & our Effort

Done ✅

**Comment by m0hitnnd** [comment]
> W.R.T [5](https://github.com/DiscardableR/DiscardableR.github.io/pull/4#issuecomment-792861561):
> 
> * We can inform reader upfront that `!` has more/less/equal precedence than `|` if he/see doesn't chose to go through the link.
> * Grammar: `operators will be grouped`
> * Also we can show the meaning of _"operators will be grouped, left or right"_ for noobs

@shahrukhalam Have tried to address all three points in my latest [commit](https://github.com/DiscardableR/DiscardableR.github.io/pull/4/commits/f48c89ccd1459353e3b9160b6d4504070cd62302)

**Comment by m0hitnnd** [comment]
> W.R.T [2](https://github.com/DiscardableR/DiscardableR.github.io/pull/4#issuecomment-792859640)
> 
> * When I was reading it, the last paragraph & the line above that (Here $0 is unwrapped value), it felt like this way is already there in Swift. May be we can clarify the **custom** part from the start.

Yes, I read it again and realised how confusing the statements were. Changed it. Thanks 👍🏼

**Comment by shahrukhalam** [comment]
@m0hitnnd 
I was having chul (scrach on the balls) to figure out a better way to test things.

# Steps For this PR:
1. create a new file in the **_posts** folder with the same name as the _ArticleName.md_ (for this PR it's **2020-03-01-custom-ternary-operator.md**)
2. copy the contents of _ArticleName.md_ from PR to the local _ArticleName.md_
3. `bundle install`
4. `rake site:watch`
5. review the article at local Server Address (most likely it will be http://127.0.0.1:4000) as printed on Terminal from step (4)

# For next PRs:
- We can directly raise PR to this repo to get rid of Step (1) & (2), also people can directly add comments on corresponding lines of the article markdown.
- Step (3) is a one time step
- Step (4) & (5) will remain same

**Comment by shahrukhalam** [comment]
LGTM 🥇 💯 ❤️

**Pull request merged**
